-- Usage visibility for the SCIM credential.
--
-- The token has no expiry and is not invalidated when the Owner who minted it
-- leaves, so the only way an operator can tell a stale key from a live one is
-- whether it is still being used. NULL means "never used since this column
-- existed", which is deliberately distinguishable from "used long ago".
--
-- A separate migration rather than an edit to 2026-07-26-000000: that one has
-- already been applied to working databases, and diesel records no checksum, so
-- an in-place edit would never re-run. Same discipline the reissue itself was
-- created to fix - see docs/scim/upgrading.md.
ALTER TABLE scim_api_key ADD COLUMN last_used_at TIMESTAMP NULL;
