-- Drop the non-unique index the UNIQUE one replaced.
--
-- 2026-07-26-000001 created (org_uuid, external_id) for lookup cost, and
-- 2026-08-08-000001 then created a UNIQUE index on exactly the same key. A
-- unique btree serves every read the non-unique one served, so what shipped was
-- two identical indexes: write amplification on every membership insert and
-- update, extra storage, and doubled index-build time during the startup
-- migration on a large install - where the whole build blocks before Rocket
-- listens.
--
-- Both were introduced on this branch, so there is no deployment that needs the
-- older one and nothing to be compatible with.
DROP INDEX IF EXISTS idx_users_organizations_org_external_id;
