-- Drop the non-unique index the UNIQUE one replaced.
--
-- 2026-07-26-000001 created (org_uuid, external_id(150)) for lookup cost, and
-- 2026-08-08-000001 then created a UNIQUE index on exactly the same key with
-- the same prefix length. A unique btree serves every read the non-unique one
-- served, so what shipped was two identical indexes: write amplification on
-- every membership insert and update, extra storage, and doubled index-build
-- time during the startup migration - which blocks before Rocket listens.
--
-- Unguarded, because mysql supports neither DROP INDEX ... IF EXISTS nor a
-- conditional form. Safe: diesel runs this only once, and the index it names is
-- created by a migration that must already have been applied to reach this one.
--
-- One statement, as every risky mysql DDL migration here is: mysql DDL is not
-- transactional, so a multi-statement migration that fails partway leaves the
-- earlier statements committed and the migration unrecorded, and every retry
-- then dies on the partial state.
DROP INDEX idx_users_organizations_org_external_id ON users_organizations;
